{
  "name": "Hello World",
  "inputs": {
    "token": {
      "description": "GitHub Token",
      "required": false,
      "default": ${{ github.token }}
    },
    "foo": {
      "description": "Foo",
      "default": "asdf"
    }
  },
  "outputs": {
    "foo": {
      "description": "some output"
    }
  },
  "description": "Greet someone and record the time",
  "runs": {
    "using": "node20",
    "main": "dist/actions-sub.mjs"
  }
}
