{
  "name": "Hello World",
  "inputs": {
    "token": {
      "description": "GitHub Token",
      "required": true,
      "default": "${{ github.token }}"
    },
    "foo": {
      "description": "Foo"
    }
  },
  "outputs": {
    "foo": {
      "description": "some output"
    },
    "workspace": {
      "description": "current workspace"
    },
    "token": {
      "description": "current token"
    }
  },
  "description": "Greet someone and record the time",
  "runs": {
    "using": "node20",
    "main": "dist/actions-sub.mjs"
  }
}
